language: python

python:
  - "3.7"
  - "3.8"

services:
  - mysql
  - redis

before_install:
  - mysql -e 'CREATE DATABASE kegbot;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv run pytest
